field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: "user_id"
ITEM_ID_FIELD: "item_id"
RATING_FIELD: None
TIME_FIELD: "timestamp"
seq_len: { "history": 20 }
LABEL_FIELD: "label"
threshold: None
NEG_PREFIX: "neg_"
load_col:
  {
    "inter": ["user_id", "item_id", "history", "timestamp"],
    "item": ["item_id", "title", "category", "subcategory"],
  }
unload_col: None
unused_col: { "inter": ["timestamp"] }
additional_feat_suffix: None
rm_dup_inter: None
val_interval: None
filter_inter_by_user_or_item: True
uesr_inter_num_interval: "[0, inf)"
item_inter_num_interval: "[0, inf)"
alias_of_user_id: None
alias_of_item_id: None
alias_of_entity_id: None
alias_of_relation_id: None
preload_weight: None
normalize_field: None
normalize_all: None
ITEM_LIST_LENGTH_FIELD: "item_length"
LIST_SUFFIX: "_list"
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: "position_id"
HEAD_ENTITY_ID_FIELD: "head_id"
TAIL_ENTITY_ID_FIELD: "tail_id"
RELATION_ID_FIELD: "relation_id"
ENTITY_ID_FIELD: "entity_id"
benchmark_filename: None
